#set colorscheme jungle
set preview_images true
set draw_borders true
set show_hidden true

set preview_images_method kitty

#version control view
set vcs_aware true
set vcs_backend_git enabled
set vcs_backend_hg disabled
set vcs_backend_bzr disabled
set vcs_backend_svn disabled

